// Marketing invoices (PDFs uploaded in Gastos → Facturas). Shared by the page
// and the AI extraction route.
import type { ExpenseCategory } from "@/lib/expenses";

export const INVOICE_BUCKET = "marketing-invoices";
export const INVOICE_MAX_BYTES = 10 * 1024 * 1024;
/** Storage paths are always generated by the app as `YYYY/<uuid>.pdf`. */
export const INVOICE_PATH_PATTERN = /^\d{4}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.pdf$/;

export type MarketingInvoice = {
  id: string;
  supplier: string;
  invoiceNumber: string | null;
  concept: string | null;
  invoiceDate: string;
  baseAmount: number;
  vatAmount: number;
  totalAmount: number;
  category: ExpenseCategory;
  businessUnitId: string | null;
  /** Set when the invoice belongs to a tracked subscription: it is then not added to totals again. */
  expenseId: string | null;
  filePath: string | null;
  fileName: string | null;
  notes: string | null;
};

/** What the AI reads from a PDF; always reviewed by a person before saving. */
export type InvoiceExtraction = {
  supplier: string;
  invoiceNumber: string | null;
  concept: string | null;
  invoiceDate: string | null;
  baseAmount: number | null;
  vatAmount: number | null;
  totalAmount: number | null;
  category: ExpenseCategory;
};

/** Amount an invoice adds to the department's spending (base, without VAT). Subscription invoices add nothing extra. */
export function invoiceSpend(invoice: MarketingInvoice): number {
  return invoice.expenseId ? 0 : invoice.baseAmount;
}

function normalise(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\b(s l u|s l|s a u|s a|slu|sl|sau|sa|ltd|limited|inc|llc|gmbh|bv|pty|plc|co)\b/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Finds the subscription an invoice most likely belongs to, by supplier name
 * (whole name contained, or same first significant word: "Canva Pty Ltd" ↔ "Canva Pro").
 * Only a suggestion: the person saving the invoice can change it.
 */
export function matchSubscription<T extends { id: string; name: string; provider: string | null; kind: string; status: string }>(supplier: string, expenses: T[]): T | null {
  const target = normalise(supplier);
  if (target.length < 3) return null;
  const targetFirst = target.split(" ")[0];
  return (
    expenses.find((expense) => {
      if (expense.kind !== "subscription") return false;
      return [expense.provider, expense.name].some((candidate) => {
        const value = candidate ? normalise(candidate) : "";
        if (value.length < 3) return false;
        const first = value.split(" ")[0];
        return value === target || target.includes(value) || value.includes(target) || (first.length >= 4 && first === targetFirst);
      });
    }) ?? null
  );
}
